In [21]:
import numpy as np

In [4]:
arr_2d = np.array([[3,6,2],[7,1,9],[5,4,8]])

In [5]:
arr_2d

array([[3, 6, 2],
       [7, 1, 9],
       [5, 4, 8]])

In [8]:
arr_2d[0][0] #First element in first row

3

In [10]:
arr_2d[2] #Entire 3rd Row

array([5, 4, 8])

In [12]:
arr_2d[2][1] #Double bracket notation

4

In [14]:
arr_2d[2,1] #Single bracke comma notation

4

In [17]:
arr_2d[:2,1:]

array([[6, 2],
       [1, 9]])

In [23]:
arr_2d[1:,:2]

array([[7, 1],
       [5, 4]])

In [24]:
arr = np.arange(1,11)

In [25]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
bool_arr = arr > 5

In [29]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [31]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [34]:
arr[arr < 3 ]

array([1, 2])

In [35]:
arr_2d = np.arange(50).reshape(5,10)

In [38]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [39]:
arr_2d[3:,3:7]

array([[33, 34, 35, 36],
       [43, 44, 45, 46]])

In [40]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])