In [54]:
import numpy as np

In [55]:
my_list = [1,2,3]

In [56]:
arr = np.array(my_list)

In [57]:
arr

array([1, 2, 3])

In [58]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [59]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [62]:
np.zeros(3)

array([0., 0., 0.])

In [63]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [64]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [65]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [66]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [67]:
np.linspace(0,8,10) 

array([0.        , 0.88888889, 1.77777778, 2.66666667, 3.55555556,
       4.44444444, 5.33333333, 6.22222222, 7.11111111, 8.        ])

In [68]:
np.eye(4) #Identitiy Matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [69]:
np.random.rand(5)

array([0.67426512, 0.11252744, 0.71992276, 0.56438947, 0.03871487])

In [70]:
np.random.rand(5,5)

array([[0.81067533, 0.05181615, 0.85241703, 0.98268815, 0.65125787],
       [0.36798595, 0.37916176, 0.78499597, 0.68231241, 0.98598378],
       [0.70382176, 0.56484461, 0.58943466, 0.59038259, 0.6292957 ],
       [0.58262484, 0.44666975, 0.94481101, 0.73797964, 0.40489628],
       [0.68458489, 0.10116723, 0.64328708, 0.12136951, 0.23726293]])

In [71]:
np.random.randn(2)

array([-0.9255131 ,  0.03666582])

In [72]:
np.random.randint(1,100,10)

array([50,  1, 57, 85,  5, 89, 19, 74, 52,  7])

In [92]:
ranarr = np.random.randint(0,50,10)
ranarr

array([31, 30, 38, 44, 25, 11, 42, 39,  6, 26])

In [76]:
ranarr.reshape(2,5)

array([[38, 16, 17, 39, 16],
       [12, 27, 48, 24, 18]])

In [ ]:
arr_new = np.arange(25)
arr_new.reshape(5,5)

In [78]:
ranarr.max()

48

In [79]:
ranarr.min()

12

In [81]:
ranarr.argmax()

7

In [83]:
ranarr.argmin()

5

In [85]:
ranarr.shape

(10,)

In [87]:
ranarr = ranarr.reshape(2,5)

In [89]:
ranarr.shape

(2, 5)

In [90]:
ranarr.dtype

dtype('int32')

In [91]:
ranarr

array([[38, 16, 17, 39, 16],
       [12, 27, 48, 24, 18]])