In [3]:
import numpy as np


In [6]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [8]:
np.arange(10,22)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [10]:
np.arange(10,22) - 10

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
len(np.arange(10,22))

12

In [16]:
my_range_array = np.arange(10,22)
my_range_array.size

12

In [18]:
np.arange(10,22).size

12

In [19]:
np.arange(10,23,5)

array([10, 15, 20])