In [3]:
import numpy as np

In [5]:
print(np.__version__)

1.16.5


In [9]:
my_list  = [-17,0,4,5,9]
my_array_from_list = np.array(my_list)
my_array_from_list

array([-17,   0,   4,   5,   9])

In [13]:
my_array_from_list * 10


array([-170,    0,   40,   50,   90])

In [16]:
my_tuple = (14, -3.54, 5 +7j)
np.array(my_tuple)

array([14.  +0.j, -3.54+0.j,  5.  +7.j])

### Difference between python and numpy data structures


In [19]:
my_tuple *6

(14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j))

In [20]:
np.array(my_tuple) * 6

array([ 84.   +0.j, -21.24 +0.j,  30.  +42.j])